language: python
python:
  - "2.7"
  - "3.2"
#  - "3.3"
#  - "3.4"
virtualenv:
  system_site_packages: true
script: nosetests
install:
  - pip install -r requirements.txt
  - pip install -r requirements-optional.txt
  - pip install -r requirements-tests.txt
addons:
  apt_packages:
  - python-dbus
  - python3-dbus
  - python-gi
  - python3-gi
